FROM prefecthq/prefect:3-python3.12
RUN pip install duckdb==1.3.2 boto3==1.40.40 playwright==1.55.0 weasyprint==66.0
RUN playwright install --with-deps chromium
RUN apt-get update && apt-get install libpangoft2-1.0-0