version: '3.9'

services:
  superset:
    image: marcorezende/superset
    ports:
      - '8088:8088'
    depends_on:
      - superset_postgres
      - superset_redis
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
    environment:
      SECRET_KEY: ${SECRET_KEY}
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}

  superset-celery:
    image: marcorezende/superset
    depends_on:
      - superset_postgres
      - superset_redis
      - superset
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
    environment:
      SECRET_KEY: ${SECRET_KEY}
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
    command: >
      celery --app=superset.tasks.celery_app:app worker --loglevel=info

  superset_postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - superset_postgres_data:/var/lib/postgresql/data
      - ./init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 3

  superset_redis:
    image: redis:latest
    volumes:
      - superset_redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  minio:
    image: 'minio/minio:RELEASE.2025-02-18T16-25-55Z'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
    command: server /data --console-address ":9001"
    volumes:
      - minio-hawkeye-data:/data

  prefect:
    image: marcorezende/prefect
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - .git_deploy.py:/app/flows/git_deploy.py
    environment:
      PREFECT_LOGGING_LEVEL: DEBUG
      PREFECT_API_URL: ${PREFECT_API_URL}
      PREFECT_API_AUTH_STRING: ${PREFECT_API_AUTH_STRING}
      PREFECT_SERVER_API_AUTH_STRING: ${PREFECT_SERVER_API_AUTH_STRING}
      CHECKLIST_FACIL_USERNAME: ${CHECKLIST_FACIL_USERNAME}
      CHECKLIST_FACIL_PASSWORD: ${CHECKLIST_FACIL_PASSWORD}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
      AWS_REGION: ${AWS_REGION}
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@superset_postgres:5432/prefect

  prefect-worker:
    image: marcorezende/prefect
    command: prefect worker start --pool "lm"
    depends_on:
      - prefect
    volumes:
      - .git_deploy.py:/app/flows/git_deploy.py
    environment:
      PREFECT_LOGGING_LEVEL: DEBUG
      PREFECT_API_URL: http://prefect:4200/api/
      PREFECT_API_AUTH_STRING: ${PREFECT_API_AUTH_STRING}
      PREFECT_SERVER_API_AUTH_STRING: ${PREFECT_SERVER_API_AUTH_STRING}
      CHECKLIST_FACIL_USERNAME: ${CHECKLIST_FACIL_USERNAME}
      CHECKLIST_FACIL_PASSWORD: ${CHECKLIST_FACIL_PASSWORD}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
      AWS_REGION: ${AWS_REGION}
volumes:
  minio-hawkeye-data:
    driver: local
  superset_postgres_data:
    driver: local
  superset_redis_data:
    driver: local
