FROM amancevice/superset:4.1.1

USER root

ARG BUILD_TRANSLATIONS=true

# backend
COPY translations/pt_BR/LC_MESSAGES/messages.mo /usr/local/lib/python3.11/site-packages/superset/translations/pt_BR/LC_MESSAGES/messages.mo
COPY translations/pt_BR/LC_MESSAGES/messages.json /usr/local/lib/python3.11/site-packages/superset/translations/pt_BR/LC_MESSAGES/messages.json

RUN apt-get update && \
    apt-get install -y firefox-esr wget unzip && \
    wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz && \
    tar -xzf geckodriver-v0.36.0-linux64.tar.gz -C /usr/local/bin && \
    chmod +x /usr/local/bin/geckodriver && \
    rm geckodriver-v0.36.0-linux64.tar.gz
RUN pip install flower==2.0.1 marshmallow==3.26.1 duckdb==1.3.1 duckdb-engine==0.17.0 pyjwt==2.9.0



USER superset